// <auto-generated />
namespace SpiralDomeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Account1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Account1));
        
        string IMigrationMetadata.Id
        {
            get { return "201910231548081_Account1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
